### ISSUE TITLE
Language choice for q/kdb+

### ISSUE THREAD

**Issue by gyorokpeter** [jeroenheijmans/advent-of-code-surveys#13]
Even though there is only a couple of people choosing it, the fact that there are multiple ways people call it makes that number even more fragmented. So we get entries for "Q", "q/kdb+", "Q/KDB+" and "Kdb+ / Q". And officially the name of the language is "q" and the software product is "kdb+" (all lowercase).

**Comment by jeroenheijmans** [comment]
Thanks for the suggestion! Slipstreamed it into #8 to consider for next year! I'll close this issue but will try hard to ping subs here when I get to handling #8.

Happy puzzling!

**Comment by gyorokpeter** [comment]
Don't add it as an IDE. kdb+ is the software product, it is just an interpreter and standard library.
However there are separately available IDEs for it such as [Kx Developer](https://code.kx.com/developer/) and [Studio for kdb+](https://github.com/finos/kdb-studio) (the latter is also called "KDB Studio"). Then there is also an [extension](https://github.com/jshinonome/vscode-q) for VSCode.

**Comment by jeroenheijmans** [comment]
Ah, thx for the heads up. I'm still slightly confused now, if I paraphrase your suggestion:

- "Q" as an extra answer to the "What languages do you use?"
- "Kx Developer" as an extra answer to the "What IDE do you use?"
- "Studio for kdb+" also as an extra "What IDE do you use?" option?

(Heads up though, whether I extend the default list, or rely on "Other..." still, depends a bit on how many people answered it as "Other" in the previous year. Either way thx for the suggestion and explanation of course!)

**Comment by gyorokpeter** [comment]
I would suggest adding "q / kdb+" as a language and merging all the replies that I mentioned above into it. Not sure if there is a need to add the IDEs but if you feel like it, "Kx Developer / Analyst" and "Studio for kdb+" would be the ones to add. (Kx Analyst is an extended version of Kx Developer that requires an enterprise license so hobby users will probably not use it).

**Comment by jeroenheijmans** [comment]
I'm setting up the 2023 edition of the survey now and will follow your suggestions: add "q / kdb+" as a language option, and leaving the IDE field as is (folks can always use the "Other" option).

I'll leave this issue open as a reminder that I need to "fold" some more custom options together. Now that I understand that "q" and "q / kdb+" are basically the same option I should update the script that interprets the submitted data.
