### ISSUE TITLE
Include "N" (number of responses) in data tables

### ISSUE THREAD

**Issue by flwyd** [jeroenheijmans/advent-of-code-surveys#23]
It would be nice to see the number of responses to each question in each year without needing to divide one of the answer counts by its percentage.

**Comment by jeroenheijmans** [comment]
Thanks for the suggestion!

Where would you suggest placing that number? I don't really want to clutter the default visualization too much (e.g. I'm not keen on putting the response count in the Legend labels or similar...).

Perhaps a tooltip for the legend items could work? Though that would not be very accessible.

Another thought would be to at least have the response count that makes up a percentage for a specific bar show up in the tooltip (that's just a bonus that will always be good), but doesn't address the original question.

To understand the suggestion better: what is the _reason_ you'd like to see this number? Perhaps if I know the "why" of it we could think a bit more out of the box?

**Comment by flwyd** [comment]
This came up for me while looking at the detail tables; I could see that 114 more people planned to use Rust for at least one problem this year versus last year, but I didn't know how that increase compares to the total increase of survey respondents without doing some arithmetic.  Perhaps the N counts would make sense as a header row for the tables.

It might also be valuable to have the total number of survey responses per year listed near the top of the page.  Maybe in the About section, or somehow associated with the year checkboxes.  The number of total survey responses helps the reader get a sense of the scale of the data and they can compare it to something like the total number of people who submitted a solution to the Day 1 puzzle (as a proxy for total AoC participation) or the number of subscribers to the subreddit.

**Comment by jeroenheijmans** [comment]
Thx for the extra input! That makes sense. I'll let it sink in and see if I can add something in the next round of updates 👍🏻

**Comment by jeroenheijmans** [comment]
Adding something of this sort in the 2023 edition, forthcoming! Hope the way I did it is to your liking. If there are suggestions afterwards I'd welcome input or PR's. For now, just a tiny bit of patience please while I finish up the 2023 results!
