### ISSUE TITLE
Consider turning "2023 Announcements" issue into more permanent issue for all future editions

### ISSUE THREAD

**Issue by Sharparam** [jeroenheijmans/advent-of-code-surveys#28]
The 2023 announcement issue is great and is how I was reminded to do the survey this year (almost missed it last year)!

But maybe it'd be better if it's just "Announcements" and re-used every year so we don't have to remember to subscribe to a new issue?

**Comment by jeroenheijmans** [comment]
Great suggestion! I think I will do that actually. Anyone who would prefer not to receive updates anymore can unsub at any time.

I'll leave this issue open for a few days to remind myself I should fix this in my workflow, but rest assured if you are subbed to the other one you'll get the right notifications until you unsub!

Happy puzzling!

**Comment by jeroenheijmans** [comment]
Thanks again for the suggestion, I've renamed and updated the issue!
